[versions]
android-compile-sdk = "33"
android-gradle-plugin = "7.4.2"
android-min-sdk = "21"
android-target-sdk = "33"
androidx-activity = "1.5.0"
binary-compatibility-validator = "0.11.1"
dependency-guard = "0.4.3"
junit-jupiter = "5.8.2"
kotlin = "1.6.21"
kotlin-coroutines = "1.6.4"

[libraries]
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin" }
android-material = 'com.google.android.material:material:1.6.1'
androidx-activity = { module = "androidx.activity:activity", version.ref = "androidx-activity" }
androidx-appcompat = 'androidx.appcompat:appcompat:1.4.2'
androidx-constraintlayout = 'androidx.constraintlayout:constraintlayout:2.1.4'
androidx-core-ktx = 'androidx.core:core-ktx:1.8.0'
androidx-lifecycle-runtime-ktx = "androidx.lifecycle:lifecycle-runtime-ktx:2.5.1"
androidx-recyclerview = 'androidx.recyclerview:recyclerview:1.2.1'
appengine-api = 'com.google.appengine:appengine-api-1.0-sdk:1.9.38'
glide = 'com.github.bumptech.glide:glide:4.12.0'
jackson-core = 'com.fasterxml.jackson.core:jackson-core:2.15.0'
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-annotations-common = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version.ref = "kotlin" }
kotlin-test-common = { module = "org.jetbrains.kotlin:kotlin-test-common", version.ref = "kotlin" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
kotlin-test-jvm = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
okhttp2 = 'com.squareup.okhttp:okhttp:2.7.5'
okhttp3 = 'com.squareup.okhttp3:okhttp:4.0.0'
servlet-api = 'javax.servlet:servlet-api:2.5'

androidx-test-junit = 'androidx.test.ext:junit:1.1.3'
androidx-test-espresso-core = 'androidx.test.espresso:espresso-core:3.4.0'
test-junit = 'junit:junit:4.13.2'


[plugins]
binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binary-compatibility-validator" }
blind-pirate-osgi = "com.github.blindpirate.osgi:0.0.6"
dependency-guard = { id = "com.dropbox.dependency-guard", version.ref = "dependency-guard" }
gradle-version-plugin = "com.github.ben-manes.versions:0.42.0"
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
maven-publish-plugin = "com.vanniktech.maven.publish:0.23.2"